### ISSUE TITLE
Error when used alongside docs-article-templates extension

### ISSUE THREAD

**Issue by TechWatching** [karigari/vscode-chat#144]
Steps to reproduce :
- Clik on sign in in the panel of Slack Chat or select sign in in the command palette
- A web page opens, connect to the slack account and accept
- The web page close and open the vs code window
- Click Ok in the Slack pop up that opens in vscode
- Nothing happens in vs code

Error in the vs code logs : 
Cannot read property 'protocol' of undefined: TypeError: Cannot read property 'protocol' of undefined
    at Function.ClientRequestParser._getUrlFromRequestOptions (D:\Tools\vscode\data\extensions\docsmsft.docs-article-templates-0.1.2\node_modules\applicationinsights\AutoCollection\ClientRequestParser.js:111:62)
    at new ClientRequestParser (D:\Tools\vscode\data\extensions\docsmsft.docs-article-templates-0.1.2\node_modules\applicationinsights\AutoCollection\ClientRequestParser.js:23:45)
    at Function.AutoCollectClientRequests.trackRequest (D:\Tools\vscode\data\extensions\docsmsft.docs-article-templates-0.1.2\node_modules\applicationinsights\AutoCollection\ClientRequests.js:68:29)
    at Object.http.request (D:\Tools\vscode\data\extensions\docsmsft.docs-article-templates-0.1.2\node_modules\applicationinsights\AutoCollection\ClientRequests.js:37:43)
    at Object.request (https.js:239:15)
    at Object.<anonymous> (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\agent-base\patch-core.js:23:20)
    at Object.request (D:\Tools\vscode\data\extensions\ms-vscode.cpptools-0.18.1\node_modules\agent-base\patch-core.js:24:20)
    at Object.https.get (D:\Tools\vscode\data\extensions\ms-vscode.cpptools-0.18.1\node_modules\agent-base\patch-core.js:35:21)
    at WebSocket.initAsClient (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\ws\lib\websocket.js:521:33)
    at new WebSocket (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\ws\lib\websocket.js:62:20)
    at RTMClient.setupWebsocket (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\@slack\client\src\RTMClient.ts:579:22)
    at RTMClient.stateMachineConfig.finity_1.default.configure.initialState.on.transitionTo.onEnter.state.submachine.finity_1.default.configure.initialState.do.onSuccess.transitionTo.onFailure.transitionTo.withCondition.transitionTo.state.onEnter (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\@slack\client\src\RTMClient.ts:138:20)
    at D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\utils\invokeEach.js:11:15
    at Array.forEach (<anonymous>)
    at invokeEach (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\utils\invokeEach.js:10:7)
    at StateMachine.enterState (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\StateMachine.js:125:32)
    at StateMachine.executeTransition (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\StateMachine.js:116:12)
    at D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\StateMachine.js:285:16
    at TaskScheduler.execute (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\TaskScheduler.js:29:7)
    at StateMachine.executeTrigger (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\StateMachine.js:282:24)
    at StateMachine.handleAsyncActionComplete (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\StateMachine.js:195:10)
    at action.then.handleComplete.error (D:\Tools\vscode\data\extensions\karigari.chat-0.5.11\node_modules\finity\lib\core\StateMachine.js:176:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by arjun27** [comment]
thanks for reporting this @TechWatching. I haven't seen anything like this before, and from the stack trace, it looks like this extension is not playing well with the [docs-article-templates](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-article-templates) extension. Can you try disabling the docs-article-templates extension to verify if the sign in works for you?

**Comment by TechWatching** [comment]
Yes your are right. If I uninstall the docs-article-templates extension it works correctly.

**Comment by arjun27** [comment]
This seems to be related: https://github.com/Microsoft/vscode-docs-authoring/issues/100

**Comment by TechWatching** [comment]
No it does not work as I have to sign-in again and the same issue occurs. Indeed you are right this issue seems directly related. Maybe we can keep this issue open while waiting for the vscode-docs issue to be solved.

**Comment by arjun27** [comment]
This seems to have been fixed in the docs-article-templates extension (
https://github.com/Microsoft/vscode-docs-authoring/issues/100). Going to close this as fixed.
