### ISSUE TITLE
Messages not sent to Slack

### ISSUE THREAD

**Issue by zetas** [karigari/vscode-chat#237]
I'm not sure if I should have posted this comment on #74 but as I think the cause is likely different I decided to open a new ticket. I authorized the app with slack and It's showing my rooms and group chats properly, the only issue is it does not send any messages I type to the slack server. None of them ever show up to my other users. I recorded a gif to show you: 
![screen recording 2018-10-11 at 01 33 pm](https://user-images.githubusercontent.com/1036810/46822906-c1625d80-cd5a-11e8-9ec6-b5fc55cc3dc6.gif)
along with the log output in case that is helpful.

And as you can see I'm able to receive messages from slack, I just can't send any.

**Comment by arjun27** [comment]
thanks for reporting this @zetas, I'm looking into this right now. unfortunately we haven't made much progress on the loader/error reporting while sending messages (#79), and so it would really help if you could open up the vs code developer tools (run the "Toggle Developer Tools" command). is there anything in the log console that looks suspicious?

**Comment by sigmer** [comment]
Same problem here.  Looks like rate limiting...
`[Extension Host] [INFO] @slack/client:WebClient0 API Call failed due to rate limiting. Will retry in 1 seconds.`

**Comment by arjun27** [comment]
thanks @sigmer. The [slack docs](https://api.slack.com/methods/chat.postMessage) suggest rate limit for sending messages is quite liberal, but it could be that a different API call is crossing the limit too.

> chat.postMessage has special rate limiting conditions. It will generally allow an app to post 1 message per second to a specific channel. There are limits governing your app's relationship with the entire workspace above that, limiting posting to several hundred messages per minute. Generous burst behavior is also granted.

does this behavior persist for you? or are you able to send messages after a cool-off period? thanks again for the help in debugging this - I'm not able to repro this, but I'll do a stress limit to validate potential rate limiting issues now

**Comment by zetas** [comment]
Thanks @sigmer. @arjun27 Him and I are actually on the same slack server and both using vscode. I'm seeing the same rate limit timeout messages in the developer console. I left my computer for about an hour and when I came back I saw the same behavior. I tried to send a message and it did not go through and I got more timeout messages in the console. Could this have something to do with having the slack desktop app open at the same time? That shouldn't really trigger a rate limit but it's the only thing I can think of.

`[Extension Host] [INFO] @slack/client:WebClient0 API Call failed due to rate limiting. Will retry in 1 seconds.`

**Comment by zetas** [comment]
Here's a screenshot of the dev console, as you can see there are quite a few of the timeout messages, it seems like it needs to wait around 8-10 minutes before it's able to send the message
<img width="777" alt="image" src="https://user-images.githubusercontent.com/1036810/46824468-ebb61a00-cd5e-11e8-9d43-0db77bcbdfa2.png">

**Comment by zetas** [comment]
I haven’t tried another workspace but ours is quite busy. We have probably
5000 users and a few hundred very active channels. Though I’m only in 5 or
6 channels total with around 1000 people in them.

Thanks,
David Della Vecchia
ddv@qubitlogic.net
http://qubitlogic.net

On Oct 11, 2018, at 4:25 PM, Arjun Attam <notifications@github.com> wrote:

Thanks @zetas <https://github.com/zetas>. Surprisingly to see the number of
logs there. I’m investigating this. Couple more questions for you if I may:

   - how many channels and users are there on this workspace?
   - have you tried signing into a different slack workspace with this
   extension?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/karigari/vscode-chat/issues/237#issuecomment-429105906>,
or mute the thread

**Comment by arjun27** [comment]
thanks @zetas. I haven't been able to isolate the issue, but I was able to identify a few improvements that to potentially fix this:

- use RTM (Websocket) for sending messages. since we have an open WS for receiving messages already, we can use the same transport for sending, and avoid any inconsistencies + additional rate limits. This was avoided earlier because of some open issues in the slack node dependency, which seem to have been fixed
- 5000 users can potentially lead to rate limiting on the `users.list` API. since we don't specify a `limit` while making the call, the slack node dependency auto-paginates the result (with 200 default page size), which will result in a burst of API calls. however, it is unclear whether this should affect the `chat.postMessage` call
- listen for `rate_limited` errors on the http client, so that we have more visibility on which calls are failing and how long to wait before the next call. [docs](https://slackapi.github.io/node-slack-sdk/web_api#rate-limit-handling)

I plan to release these improvements in the coming releases, will keep you posted.

**Comment by zetas** [comment]
Thanks for the updates, It's much appreciated. If you need any other debug info or help testing new versions please let me know 👍

**Comment by arjun27** [comment]
@zetas, @sigmer - I have released 0.7.1 with these improvements. Let me know if you get a chance to try it out, thanks!

**Comment by zetas** [comment]
Now it doesn't load at all after updating: 

` ERR Cannot destructure property `isDeleted` of 'undefined' or 'null'.: TypeError: Cannot destructure property `isDeleted` of 'undefined' or 'null'.
    at memberUsers.filter (/Users/david/.vscode/extensions/karigari.chat-0.7.2/out/slack/client.js:291:73)
    at Array.filter (<anonymous>)
    at channels.map.channel (/Users/david/.vscode/extensions/karigari.chat-0.7.2/out/slack/client.js:291:66)
    at Array.map (<anonymous>)
    at SlackAPIClient.<anonymous> (/Users/david/.vscode/extensions/karigari.chat-0.7.2/out/slack/client.js:263:22)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/david/.vscode/extensions/karigari.chat-0.7.2/out/slack/client.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by arjun27** [comment]
Thanks for checking @zetas. Looks like the user limit doesn't play well with loading the channels - sorry about this issue. I have just released a fix for this in 0.7.3
