### ISSUE TITLE
unable to chat on discord

### ISSUE THREAD

**Issue by ThomasKagan** [karigari/vscode-chat#380]
the Discord panel is completely blank, nothing under "Workspaces," "Unreads," "Channels," etc. When I do "Chat: Open > Reload Channels... > Discord" nothing changes. I know I entered my token right because when I go to "Chat: Change Workspace > Discord" I see all of my account's channels in "select provider."

I'm on Windows 10.

**Comment by arjun27** [comment]
Thanks @ThomasKagan. Is this a regression? Did it work for you earlier?

**Comment by ThomasKagan** [comment]
Nope! Just never been able to

**Comment by forrestblade** [comment]
It doesn't work for me either. Same issue, correct token but once I choose the server I want to chat on, it doesn't load any of the channels

**Comment by phydesmith** [comment]
Hello - I am having a similar problem. I can see all of my guilds in "workspace" tab but nothing under channels, unreads etc.

**Comment by phydesmith** [comment]
I just want to follow up as maybe I'm using this software incorrectly.

Is this able to connect to Discord independently of Live Share session (like a chat client)- or does Live Share need to be used to get this to work?

**Comment by arjun27** [comment]
Thanks @phydesmith. Using Discord does not rely on Live Share. Once your Discord auth is configured, the extension should work as a client for Discord.

**Comment by phydesmith** [comment]
Ok - it works now.

I ended up restarting VScode. 
I clicked on the Discord icon on the lefthand pane and it was empty. 
I opened the command palette and did chat: open
I saw channel options now so I clicked one and it opened it up. 

So, maybe I just did it incorrectly, I apologize for necroposting.

**Comment by arjun27** [comment]
Thanks for sharing - the channel list should populate without running the additional command, and these steps will help me debug.

**Comment by Fireant456** [comment]
I use to be able to use the discord functionality but maybe a month or two ago it stopped populating the sidebar. I got it to load maybe once using the steps mentioned above but haven't gotten it back since. I would love to use the extension but it seems to be crashing the extension handler as well from time to time.

**Comment by Fireant456** [comment]
`[2019-08-02 23:37:59.143] [renderer1] [error] Cannot read property 'handle' of undefined: TypeError: Cannot read property 'handle' of undefined
	at module.exports.e.exports.handle (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:193026)
	at module.exports.e.exports.handle (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:184792)
	at u.onPacket (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:84125)
	at u.onMessage (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:83517)
	at v.i (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:195261)
	at v.emit (events.js:182:13)
	at module.exports.e.exports.module.exports.setSocket._receiver.onmessage.e [as onmessage] (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:96572)
	at module.exports.e.exports.dataMessage (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:108048)
	at module.exports.e.exports.getData (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:107304)
	at module.exports.e.exports.startLoop (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:104881)
	at module.exports.e.exports.add (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:104674)
	at TLSSocket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at TLSSocket.Readable.push (_stream_readable.js:219:10)
	at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-08-02 23:38:31.353] [renderer1] [error] Cannot read property 'handle' of undefined: TypeError: Cannot read property 'handle' of undefined
	at module.exports.e.exports.handle (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:193026)
	at module.exports.e.exports.handle (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:184792)
	at module.exports.e.exports.handleQueue.queue.forEach (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:184077)
	at Array.forEach (<anonymous>)
	at module.exports.e.exports.handleQueue (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:184056)
	at module.exports.e.exports.handle (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:186653)
	at module.exports.e.exports.handle (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:184792)
	at u.onPacket (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:84125)
	at u.onMessage (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:83517)
	at v.i (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:232:195261)
	at v.emit (events.js:182:13)
	at module.exports.e.exports.module.exports.setSocket._receiver.onmessage.e [as onmessage] (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:96572)
	at module.exports.e.exports.dataMessage (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:108048)
	at module.exports.e.exports.getData (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:107304)
	at module.exports.e.exports.startLoop (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:104881)
	at module.exports.e.exports.add (C:\Users\max32\.vscode\extensions\karigari.chat-0.16.0\out\extension.js:151:104674)
	at TLSSocket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at TLSSocket.Readable.push (_stream_readable.js:219:10)
	at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

This was my log at the time of my extensions crashing tonight when trying again...

**Comment by PXVC** [comment]
Has anyone fixed that error yet?
